### ISSUE TITLE
About 't1-extensive'

### ISSUE THREAD

**Issue by czTLG** [aramis-lab/AD-DL#1]
Will the section on 't1-extensive' be updated?
If so, when will it be updated?

**Comment by mdiazmel** [comment]
Hi @czTLG,

> Will the section on 't1-extensive' be updated?
> If so, when will it be updated?

This repository will be archived soon. It's keep like this only for historical reasons.
 If you want to get a more recent version, please visit [clinicadl](https://github.com/aramis-lab/clinicadl) and/or [clinica](https://github.com/aramis-lab/clinica) repositories, there are several tools to perform `t1-extensive` preprocessing.
